
services:
  ubuntu-base-hl:
    build: .
    image: hackinglab/ubuntu-base-hl:latest
    environment:
      - HL_USER_USERNAME=hacker
      #- HL_USER_PASSWORD=compass
      #- HL_ROOT_PASSWORD=<change-me>

